feat: add Integrity and Hygiene ratings if present
sonatype-nexus-community/sonatype-platform-browser-extension pull request #131
Opened 2024-08-27 15:43 UTC by maurycupitt

Add Integrity and Hygiene ratings if present.

Both Integrity and Hygiene: https://central.sonatype.com/artifact/org.apache.struts/struts2-core/6.1.2
Hygiene Only: https://central.sonatype.com/artifact/org.apache.struts/struts2-core/2.5.29
Integrity Only: https://www.npmjs.com/package/express/v/4.19.2

2024-08-27 16:07 UTC, madpah commented
We need to add message entries for the other languages @maurycupitt

2024-08-27 16:14 UTC, madpah requested changes

2024-08-27 16:14 UTC, madpah commented on public/_locales/en/messages.json
We need to add translations.

2024-08-27 17:47 UTC, maurycupitt commented on public/_locales/en/messages.json
done

2024-08-28 08:58 UTC, madpah approved these changes

2024-08-28 08:59 UTC, madpah commented
Merge on hold until we have reviewed some account validation settings with Google and Microsoft @maurycupitt.

2024-09-03 14:37 UTC, merged

2024-09-03 14:40 UTC, brent-spiner commented
:tada: This PR is included in version 2.19.0 :tada:

The release is available on:
- [Chrome Web Store](https://chrome.google.com/webstore/detail/kahnhlonadjlllgnilndafpajaiepdag)
- `v2.19.0`
- [GitHub release](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/releases/tag/v2.19.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: