Migrate from CircleCI to GitHub Actions
sonatype-nexus-community/sonatype-platform-browser-extension pull request #137
Opened 2024-10-31 08:29 UTC by madpah

Resolves #134.

2024-11-01 13:29 UTC, maurycupitt requested changes

2024-11-01 13:29 UTC, maurycupitt commented on .github/workflows/release.yml
> +                  sed -i -r "s/GA_MEASUREMENT_ID/$GA_MEASUREMENT_ID/g" src/utils/AnalyticsConfg.ts &&
Need secrets assigned

2024-11-01 13:29 UTC, maurycupitt commented on .github/workflows/release.yml
> +        name: Build and Publish Docker Image
```suggestion
        name: Build, Release and Publish
```

2024-11-14 09:07 UTC, madpah commented on .github/workflows/release.yml
> +                  sed -i -r "s/GA_MEASUREMENT_ID/$GA_MEASUREMENT_ID/g" src/utils/AnalyticsConfg.ts &&
Added

2024-11-14 09:07 UTC, merged